server:
  port: 8090

spring:
  application:
    name: "exchange-processing-service"

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/processing
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db
    url: jdbc:postgresql://localhost:5433/processing
    user: postgres
    password: postgres

service:
  currency:
    url: "http://localhost:8085"

eureka:
  client:
    enabled: false
    defaultZone: "http://localhost:8761/eurika"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG